version: '3.1'

services:

  discovery-server-service:
    container_name: discovery-server-service
    build:
      context: .
      dockerfile: Dockerfile_OLD
    ports:
      - "8761:8761"
#    networks:
#      - localeconnect-network
#
#
#networks:
#  localeconnect-network:
#    driver: bridge