server:
  port: 8084

spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://localeconnect-database.postgres.database.azure.com:5432/consolidatedDB
    username: ***********
    password: ***********
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: SpringHikariCP
      max-lifetime: 2000000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: localeconnect.team@gmail.com
    password: dosa yoeh rbtc nzvb
    properties.mail.smtp:
       auth: true
       starttls.enable: true


  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

jwt:
  secret: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"
