server:
  port: 8081

spring:
  application:
    name: feed

  datasource:
    url: jdbc:postgresql://localeconnect-database.postgres.database.azure.com:5432/consolidatedDB
    username: ***********
    password: ***********
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: SpringHikariCP
      max-lifetime: 2000000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#  data:
#    redis:
#      host: redis-service
#      port: 6379
#      username: guest
#      password: guest

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
