server:
  port : 8003

spring:
  application:
    name: chat

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true