server:
  port: 8761

spring:
  application:
    name: discovery-server

eureka:
  instance:
    hostname: "${HOSTNAME:localhost}.eureka"
    appname: eureka-server
  client:
    registerWithEureka: false
    fetchRegistry: false
